import React from 'react';
import './Text.css';

class Article extends React.Component {
  render() {
    return (
      <div className="article shadow">
        <h1>Depth First Search</h1>
        <h3>Lorem ipsum dolor sit amet.</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime, molestias quia! Est ullam ipsam magni, enim dolor eaque facere nobis sapiente laborum odit sint dolore recusandae numquam quibusdam iste molestias assumenda velit. Voluptatem, repudiandae. Architecto ipsa quos temporibus, beatae, doloribus minus voluptas cum tenetur esse cupiditate velit dolor placeat, repellat libero? Quibusdam illo magnam aliquam laborum saepe consectetur ipsum perferendis, iste velit tenetur debitis nisi minus est quod officiis! Sequi voluptate, laudantium unde quasi quidem dicta ex corporis ad neque repellat eius nihil blanditiis assumenda porro? Omnis consequatur vitae deserunt quo recusandae ut, alias eaque quisquam velit assumenda possimus sit quam veniam perspiciatis adipisci distinctio quasi tempora maxime expedita in tenetur nesciunt obcaecati deleniti? Maiores rerum fugit eveniet at omnis harum ex deserunt voluptatem aspernatur debitis veniam, possimus, magni voluptatibus culpa ratione, quas delectus doloribus et nisi tempore mollitia amet officia. Expedita natus, pariatur nisi recusandae atque adipisci voluptatem eos accusamus quia necessitatibus, fuga impedit temporibus culpa quisquam sint repellat iure, labore quasi quas. Quidem vel nulla deleniti temporibus in voluptatum ratione nobis sapiente sequi omnis ad magni voluptatibus, earum perspiciatis quaerat, dolore, eaque repellat amet cum aperiam sunt fugiat. Eligendi perferendis temporibus magni aut maxime corporis adipisci? Commodi, dolorum!</p>
        <h3>Porro quam ipsum iste laudantium?</h3>
        <p>Ipsum assumenda at rem repellendus et, inventore placeat quae? Dolorem vero accusantium voluptatibus consectetur atque cum dolor illum, nulla quibusdam maiores ipsum nihil explicabo porro cumque unde necessitatibus a voluptatum? Quam explicabo fugit ipsam officiis, reiciendis assumenda quidem enim qui voluptates ipsum similique dolor, cumque commodi. Quos dolores mollitia quidem! Numquam, expedita repellendus vitae praesentium debitis accusamus architecto minima perferendis! Harum at distinctio consequuntur cupiditate vel recusandae, quae accusamus id ratione eveniet ad soluta impedit quasi. Sunt hic expedita maiores ab, nam eveniet magnam ex nesciunt corrupti natus dolor, quas, reprehenderit eum provident dolorum mollitia modi dolore nostrum. Dolore a possimus cum! Ea facilis atque dolorem qui consequuntur accusantium necessitatibus laboriosam velit error maiores? Quisquam similique, id a sit modi officiis provident. Aliquid eum autem tempora, repudiandae tempore molestiae quo itaque corporis, incidunt, porro saepe earum ea culpa libero. Dolor molestias vel porro possimus earum voluptatem distinctio reprehenderit sequi repudiandae expedita? Corporis earum accusamus nisi ipsam. Consequuntur nesciunt, perspiciatis nihil quae id soluta dolores neque distinctio itaque ut sequi. Aperiam perspiciatis vitae dolorem consectetur. Quo quas voluptate eius perspiciatis nulla illum doloribus, iure ratione alias explicabo cum quia minima iusto nesciunt fuga. Magnam sunt quia deserunt, similique voluptas in saepe.</p>
        <h3>Id aspernatur eum earum repudiandae.</h3>
        <p>Voluptas fugit culpa pariatur, delectus fugiat dolorem deserunt nisi ut unde officiis id modi quam mollitia commodi quidem iste, voluptatum laborum animi voluptatem cupiditate. Aut autem quos placeat doloremque illo maxime consequuntur modi, cumque alias eligendi quia neque delectus in blanditiis. Possimus, illo cum. Sed, explicabo porro sapiente officia dolorum soluta totam qui maxime ipsam quo expedita, amet nobis corporis? Totam adipisci eaque omnis at ullam libero nulla officiis consequuntur alias enim corrupti vitae doloremque assumenda unde sit rerum, minus ratione! Corrupti dolorem quibusdam quaerat vel ipsum nisi deleniti quisquam beatae saepe nesciunt, est porro veritatis voluptate perspiciatis similique? Veniam, iste perferendis! Illo dignissimos, sit libero aut magni velit veniam inventore consequatur. Eum provident aperiam suscipit sint natus obcaecati fuga corrupti quae optio in mollitia deserunt unde dolorum, impedit eligendi laboriosam iure ullam consequuntur at assumenda nesciunt. Consectetur quibusdam ut, odio voluptatum harum culpa rerum inventore aspernatur accusamus est pariatur placeat nesciunt illum aperiam accusantium beatae neque, nostrum, porro nobis eveniet eum asperiores. Cumque neque temporibus quibusdam eaque? Dolor saepe sint tenetur labore eius enim exercitationem reiciendis quaerat sequi rerum, maiores architecto distinctio repellat iure odit eum, dignissimos fugit omnis est sapiente! Dignissimos iusto, iure magnam perferendis est quia itaque!</p>
        <p>Voluptas fugit culpa pariatur, delectus fugiat dolorem deserunt nisi ut unde officiis id modi quam mollitia commodi quidem iste, voluptatum laborum animi voluptatem cupiditate. Aut autem quos placeat doloremque illo maxime consequuntur modi, cumque alias eligendi quia neque delectus in blanditiis. Possimus, illo cum. Sed, explicabo porro sapiente officia dolorum soluta totam qui maxime ipsam quo expedita, amet nobis corporis? Totam adipisci eaque omnis at ullam libero nulla officiis consequuntur alias enim corrupti vitae doloremque assumenda unde sit rerum, minus ratione! Corrupti dolorem quibusdam quaerat vel ipsum nisi deleniti quisquam beatae saepe nesciunt, est porro veritatis voluptate perspiciatis similique? Veniam, iste perferendis! Illo dignissimos, sit libero aut magni velit veniam inventore consequatur. Eum provident aperiam suscipit sint natus obcaecati fuga corrupti quae optio in mollitia deserunt unde dolorum, impedit eligendi laboriosam iure ullam consequuntur at assumenda nesciunt. Consectetur quibusdam ut, odio voluptatum harum culpa rerum inventore aspernatur accusamus est pariatur placeat nesciunt illum aperiam accusantium beatae neque, nostrum, porro nobis eveniet eum asperiores. Cumque neque temporibus quibusdam eaque? Dolor saepe sint tenetur labore eius enim exercitationem reiciendis quaerat sequi rerum, maiores architecto distinctio repellat iure odit eum, dignissimos fugit omnis est sapiente! Dignissimos iusto, iure magnam perferendis est quia itaque!</p>
      </div>
    );
  }
}

export default Article;